.TH "C3DCubeModel" 3 "Sun Nov 22 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C3DCubeModel \- <Common Header  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <C3DCubeModel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCreateModel\fP (float size)"
.br
.ti -1c
.RI "void \fBDeleteModel\fP ()"
.br
.ti -1c
.RI "void \fBDrawModel\fP (wzMatrix *pView, wzMatrix *pProj, wzVector3 *gap=NULL)"
.br
.ti -1c
.RI "void \fBDrawARModel\fP (OVR::OvMarkerData *data, wzMatrix *pProj, wzVector3 *gap=NULL)"
.br
.in -1c
.SH "Detailed Description"
.PP 
<Common Header 

.SH "Author"
.PP 
Generated automatically by Doxygen for OvrvisionSDK from the source code\&.
