.TH "C:/Users/Wizapply1/Desktop/OvrvisionProSDK/include Directory Reference" 3 "Tue Nov 24 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Wizapply1/Desktop/OvrvisionProSDK/include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBovrvision_ar\&.h\fP"
.br
.ti -1c
.RI "file \fBovrvision_pro\&.h\fP"
.br
.in -1c
