.TH "DepthBuffer" 3 "Sun Nov 22 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DepthBuffer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDepthBuffer\fP (ID3D11Device *Device, int sizeW, int sizeH, int sampleCount=1)"
.br
.ti -1c
.RI "\fBDepthBuffer\fP (Sizei size, int sampleCount)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ID3D11DepthStencilView * \fBTexDsv\fP"
.br
.ti -1c
.RI "GLuint \fBtexId\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OvrvisionSDK from the source code\&.
