.TH "IndexBuffer" 3 "Sun Nov 22 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IndexBuffer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIndexBuffer\fP (void *indices, size_t size)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLuint \fBbuffer\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OvrvisionSDK from the source code\&.
