.TH "Material" 3 "Sun Nov 22 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Material \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBMAT_WRAP\fP = 1, \fBMAT_WIRE\fP = 2, \fBMAT_ZALWAYS\fP = 4, \fBMAT_NOCULL\fP = 8, \fBMAT_TRANS\fP = 16 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaterial\fP (\fBTexture\fP *t, DWORD flags=MAT_WRAP|MAT_TRANS, D3D11_INPUT_ELEMENT_DESC *vertexDesc=NULL, int numVertexDesc=3, char *vertexShader=NULL, char *pixelShader=NULL, int vSize=24)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ID3D11VertexShader * \fBD3DVert\fP"
.br
.ti -1c
.RI "ID3D11PixelShader * \fBD3DPix\fP"
.br
.ti -1c
.RI "\fBTexture\fP * \fBTex\fP"
.br
.ti -1c
.RI "ID3D11InputLayout * \fBInputLayout\fP"
.br
.ti -1c
.RI "UINT \fBVertexSize\fP"
.br
.ti -1c
.RI "ID3D11SamplerState * \fBSamplerState\fP"
.br
.ti -1c
.RI "ID3D11RasterizerState * \fBRasterizer\fP"
.br
.ti -1c
.RI "ID3D11DepthStencilState * \fBDepthState\fP"
.br
.ti -1c
.RI "ID3D11BlendState * \fBBlendState\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OvrvisionSDK from the source code\&.
