.TH "OculusTexture" 3 "Sun Nov 22 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OculusTexture \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBInit\fP (ovrHmd _hmd, int sizeW, int sizeH)"
.br
.ti -1c
.RI "void \fBAdvanceToNextTexture\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ovrHmd \fBhmd\fP"
.br
.ti -1c
.RI "ovrSwapTextureSet * \fBTextureSet\fP"
.br
.ti -1c
.RI "ID3D11RenderTargetView * \fBTexRtv\fP [TextureCount]"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBTextureCount\fP = 2"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OvrvisionSDK from the source code\&.
