.TH "OVR::OvrvisionProOpenCL" 3 "Tue Nov 24 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVR::OvrvisionProOpenCL \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOvrvisionProOpenCL\fP (int width, int height, enum SHARING_MODE mode=NONE)"
.br
.ti -1c
.RI "bool \fBLoadCameraParams\fP (const char *filename)"
.br
.ti -1c
.RI "bool \fBLoadCameraParams\fP (\fBOvrvisionSetting\fP *ovrset)"
.br
.ti -1c
.RI "void \fBDemosaic\fP (const ushort *src, cl_event *execute=NULL)"
.br
.ti -1c
.RI "void \fBDemosaic\fP (const ushort *src, cl_mem left, cl_mem right, cl_event *execute=NULL)"
.br
.ti -1c
.RI "void \fBDemosaic\fP (const ushort *src, uchar *left, uchar *right)"
.br
.ti -1c
.RI "void \fBDemosaic\fP (const ushort *src, Mat &left, Mat &right)"
.br
.ti -1c
.RI "void \fBDemosaic\fP (const Mat src, Mat &left, Mat &right)"
.br
.ti -1c
.RI "void \fBDemosaicRemap\fP (const ushort *src, cl_event *execute=NULL)"
.br
.ti -1c
.RI "void \fBDemosaicRemap\fP (const ushort *src, cl_mem left, cl_mem right, cl_event *execute=NULL)"
.br
.ti -1c
.RI "void \fBDemosaicRemap\fP (const ushort *src, uchar *left, uchar *right)"
.br
.ti -1c
.RI "void \fBDemosaicRemap\fP (const ushort *src, Mat &left, Mat &right)"
.br
.ti -1c
.RI "void \fBDemosaicRemap\fP (const Mat src, Mat &left, Mat &right)"
.br
.ti -1c
.RI "cl_device_id \fBSelectGPU\fP (const char *platform, const char *version)"
.br
.ti -1c
.RI "void \fBGrayscale\fP (uchar *left, uchar *right, enum SCALING scale)"
.br
.ti -1c
.RI "cl_mem \fBCreateGLTexture2D\fP (GLuint texture, int width, int height, GLenum pixelFormat=GL_RGBA, GLenum dataType=GL_UNSIGNED_BYTE)"
.br
.ti -1c
.RI "cl_mem \fBCreateD3DTexture2D\fP (int width, int height)"
.br
.ti -1c
.RI "void \fBcreateProgram\fP (const char *filename, bool binary=false)"
.br
.ti -1c
.RI "int \fBsaveBinary\fP (const char *filename)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "cl_platform_id \fB_platformId\fP"
.br
.ti -1c
.RI "cl_device_id \fB_deviceId\fP"
.br
.ti -1c
.RI "cl_context \fB_context\fP"
.br
.ti -1c
.RI "cl_program \fB_program\fP"
.br
.ti -1c
.RI "cl_kernel \fB_demosaic\fP"
.br
.ti -1c
.RI "cl_kernel \fB_remap\fP"
.br
.ti -1c
.RI "cl_command_queue \fB_commandQueue\fP"
.br
.ti -1c
.RI "cl_image_format \fB_format16UC1\fP"
.br
.ti -1c
.RI "cl_image_format \fB_format8UC4\fP"
.br
.ti -1c
.RI "cl_image_format \fB_formatMap\fP"
.br
.ti -1c
.RI "cl_int \fB_errorCode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OvrvisionSDK from the source code\&.
