.TH "OVR::ROI" 3 "Wed Dec 2 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVR::ROI \- \fBROI\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ovrvision_pro\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBoffsetX\fP"
.br
.ti -1c
.RI "int \fBoffsetY\fP"
.br
.RI "\fIOffsetX\&. \fP"
.ti -1c
.RI "unsigned int \fBwidth\fP"
.br
.RI "\fIOffsetY\&. \fP"
.ti -1c
.RI "unsigned int \fBheight\fP"
.br
.RI "\fIWidth\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBROI\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for OvrvisionSDK from the source code\&.
