.TH "OVR::OvrvisionCalibration" 3 "Tue Nov 24 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVR::OvrvisionCalibration \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOvrvisionCalibration\fP (int img_size_w, int img_size_h, int pattern_size_w, int pattern_size_h, double chess_length_mm, int max_chess_count=10000)"
.br
.ti -1c
.RI "int \fBInitializeCalibration\fP (int img_size_w, int img_size_h, int pattern_size_w, int pattern_size_h, double chess_length_mm, int max_chess_count=10000)"
.br
.ti -1c
.RI "bool \fBFindChessBoardCorners\fP (const unsigned char *left_img, const unsigned char *right_img)"
.br
.ti -1c
.RI "void \fBDrawChessboardCorners\fP (const unsigned char *src_img, unsigned char *dest_img, Cameye eye)"
.br
.ti -1c
.RI "void \fBSolveStereoParameter\fP ()"
.br
.ti -1c
.RI "void \fBSaveCalibrationParameter\fP (\fBOvrvisionPro\fP *ovrpro)"
.br
.ti -1c
.RI "int \fBGetImageCount\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::vector< cv::Point2f > > \fBm_subpix_corners_left\fP"
.br
.ti -1c
.RI "std::vector< std::vector< cv::Point2f > > \fBm_subpix_corners_right\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   cv::Mat \fBintrinsic\fP"
.br
.ti -1c
.RI "   cv::Mat \fBdistortion\fP"
.br
.ti -1c
.RI "   cv::Mat \fBR\fP"
.br
.ti -1c
.RI "   cv::Mat \fBP\fP"
.br
.ti -1c
.RI "} \fBm_cameraCalibration\fP [\fBOV_CAMNUM\fP]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OvrvisionSDK from the source code\&.
