.TH "OVR::ov_st_vector3d" 3 "Tue Dec 29 2015" "Version 1.3" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVR::ov_st_vector3d \- Vector3D structure for \fBov_st_marker_data\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ovrvision_ar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   float \fBv\fP [3]"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      float \fBx\fP"
.br
.ti -1c
.RI "      float \fBy\fP"
.br
.ti -1c
.RI "      float \fBz\fP"
.br
.ti -1c
.RI "   } "
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Vector3D structure for \fBov_st_marker_data\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for OvrvisionSDK from the source code\&.
