.TH "OVR::ov_st_marker_data" 3 "Tue Dec 29 2015" "Version 1.3" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVR::ov_st_marker_data \- Ovrvision AR Marker data structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ovrvision_ar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "\fBOvVector3D\fP \fBtranslate\fP"
.br
.RI "\fIMarkerID\&. \fP"
.ti -1c
.RI "\fBOvVector4D\fP \fBquaternion\fP"
.br
.RI "\fIPosition data\&. \fP"
.ti -1c
.RI "\fBOvVector2D\fP \fBcenterPtOfImage\fP"
.br
.RI "\fIRotation data\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Ovrvision AR Marker data structure\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for OvrvisionSDK from the source code\&.
