.TH "OVR::OvrvisionTracking" 3 "Tue Dec 1 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OVR::OvrvisionTracking \- \fBOvrvisionPro\fP Hand tracking class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ovrvision_tracking\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOvrvisionTracking\fP (int w, int h, float focalpoint)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "\fB~OvrvisionTracking\fP ()"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "void \fBSetImageBGRA\fP (unsigned char *pLeftImage, unsigned char *pRightImage)"
.br
.RI "\fISet the pointer of image data\&. \fP"
.ti -1c
.RI "void \fBSetImageOpenCVImage\fP (ovMat *pLeftImageMat, ovMat *pRightImageMat)"
.br
.RI "\fISet the pointer of OpenCV Mat data\&. \fP"
.ti -1c
.RI "void \fBRender\fP ()"
.br
.RI "\fIRun hand detection processing\&. \fP"
.ti -1c
.RI "void \fBSetHue\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBOvrvisionPro\fP Hand tracking class\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OVR::OvrvisionTracking::OvrvisionTracking (int w, int h, float focalpoint)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIw\fP Image width\&. 
.br
\fIh\fP Image height\&. 
.br
\fIfocalpoint\fP Image focal point\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void OVR::OvrvisionTracking::SetImageBGRA (unsigned char * pLeftImage, unsigned char * pRightImage)"

.PP
Set the pointer of image data\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpLeftImage\fP LeftImage buffer pointer\&. 
.br
\fIpRightImage\fP RightImage buffer pointer\&. 
.RE
.PP

.SS "void OVR::OvrvisionTracking::SetImageOpenCVImage (ovMat * pLeftImageMat, ovMat * pRightImageMat)"

.PP
Set the pointer of OpenCV Mat data\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpLeftImageMat\fP Left OpenCV Mat pointer\&. 
.br
\fIpRightImageMat\fP Right OpenCV Mat pointer\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for OvrvisionSDK from the source code\&.
