.TH "page1" 3 "Mon Dec 7 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
page1 \- Using the Tools 
Introduce how to use the tool attached to OvrvisionPro SDK\&. OvrvisionProに付属するツールの使い方についてご紹介します。
.SH "Calibration tool"
.PP
.PP
Program path :
.IP "\(bu" 2
tools -> calibration\&.exe(Windows)
.IP "\(bu" 2
tools -> calibration\&.app(Mac OSX)
.PP
.SS "How to Use"
.PP
The usage should confirm the following video\&. 
.br
 使い方は、下記のビデオをご確認してください。
.br
 \fBURL : \fChttps://www\&.youtube\&.com/watch?v=wSjqImFmxDY\fP\fP
.SH "AR Marker make tool"
.PP
.IP "\(bu" 2
Coming Soon 
.PP

