.TH "page4" 3 "Fri Dec 11 2015" "Version 1.2" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
page4 \- Release Notes 

.SH "Ovrvision SDK v1\&.2"
.PP
Date : 10/Dec/2015
.br
 \fBNotes\fP
.IP "\(bu" 2
Add the function of errors display\&.
.IP "\(bu" 2
Intensified AR and Tracking function\&.
.IP "\(bu" 2
Add mask functions in Unity\&.
.IP "\(bu" 2
Bug of the calibration tools was fixed\&.
.PP
.PP
\fBUnimplementeds and issue\fP
.IP "\(bu" 2
Mac OSX support (in a few days)
.IP "\(bu" 2
Linux OS support
.IP "\(bu" 2
Unreal Engine 4
.IP "\(bu" 2
The memory leak of OpenCL\&. (NVIDIA Driver) 
.PP
.SH "Ovrvision SDK v1\&.1"
.PP
Date : 07/Dec/2015
.br
 \fBNotes\fP
.IP "\(bu" 2
The memory leak was resolved\&.
.IP "\(bu" 2
OvrvisionTracking was released\&.
.IP "\(bu" 2
The fault which OvrvisionPro does not start was corrected\&.
.PP
.PP
\fBUnimplementeds and issue\fP
.IP "\(bu" 2
Mac OSX support (in a few days)
.IP "\(bu" 2
Linux OS support
.IP "\(bu" 2
Unreal Engine 4
.IP "\(bu" 2
The memory leak of OpenCL\&. (NVIDIA Driver)
.PP
.SH "Ovrvision SDK v1\&.01"
.PP
Date : 02/Dec/2015
.br
 \fBNotes\fP
.IP "\(bu" 2
Fixed bugs\&.
.IP "\(bu" 2
OpenCL system is choose suitable GPU\&.
.PP
.PP
\fBUnimplementeds and issue\fP
.IP "\(bu" 2
OvrvisionTracking class : Hand tracking (in a few days)
.IP "\(bu" 2
Mac OSX support (in a few days)
.IP "\(bu" 2
Linux OS support
.IP "\(bu" 2
Unreal Engine 4
.PP
.SH "Ovrvision SDK v1\&.0"
.PP
Date : 01/Dec/2015
.br
 \fBNotes\fP
.IP "\(bu" 2
First release\&.
.PP
.PP
\fBUnimplementeds and issue\fP
.IP "\(bu" 2
OvrvisionTracking class : Hand tracking (in a few days)
.IP "\(bu" 2
Mac OSX support (in a few days)
.IP "\(bu" 2
Linux OS support
.IP "\(bu" 2
Unreal Engine 4 
.PP

