.TH "page4" 3 "Tue Dec 1 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
page4 \- Release Notes 

.SH "Ovrvision SDK v1\&.0"
.PP
\fBNotes\fP
.IP "\(bu" 2
First release\&.
.PP
.PP
\fBUnimplementeds and issue\fP
.IP "\(bu" 2
OvrvisionTracking class : Hand tracking (in a few days)
.IP "\(bu" 2
Mac OSX support (in a few days)
.IP "\(bu" 2
Linux OS support
.IP "\(bu" 2
Unreal Engine 4 
.PP

