.TH "Scene" 3 "Sun Nov 22 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scene \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAdd\fP (\fBModel\fP *n)"
.br
.ti -1c
.RI "void \fBRender\fP (XMMATRIX *projView, float R, float G, float B, float A, bool standardUniforms)"
.br
.ti -1c
.RI "void \fBInit\fP (bool includeIntensiveGPUobject)"
.br
.ti -1c
.RI "\fBScene\fP (bool includeIntensiveGPUobject)"
.br
.ti -1c
.RI "void \fBRelease\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (\fBModel\fP *n)"
.br
.ti -1c
.RI "void \fBRender\fP (Matrix4f view, Matrix4f proj)"
.br
.ti -1c
.RI "GLuint \fBCreateShader\fP (GLenum type, const GLchar *src)"
.br
.ti -1c
.RI "void \fBInit\fP (int includeIntensiveGPUobject)"
.br
.ti -1c
.RI "\fBScene\fP (bool includeIntensiveGPUobject)"
.br
.ti -1c
.RI "void \fBRelease\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBModel\fP * \fBModels\fP [MAX_MODELS]"
.br
.ti -1c
.RI "int \fBnumModels\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBMAX_MODELS\fP = 100"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OvrvisionSDK from the source code\&.
