.TH "ShaderFill" 3 "Sun Nov 22 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShaderFill \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShaderFill\fP (GLuint vertexShader, GLuint pixelShader, \fBTextureBuffer\fP *_texture)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLuint \fBprogram\fP"
.br
.ti -1c
.RI "\fBTextureBuffer\fP * \fBtexture\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OvrvisionSDK from the source code\&.
