.TH "Texture" 3 "Sun Nov 22 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Texture \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBAUTO_WHITE\fP = 1, \fBAUTO_WALL\fP, \fBAUTO_FLOOR\fP, \fBAUTO_CEILING\fP, \fBAUTO_GRID\fP, \fBAUTO_GRADE_256\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (int sizeW, int sizeH, bool rendertarget, int mipLevels, int sampleCount)"
.br
.ti -1c
.RI "\fBTexture\fP (int sizeW, int sizeH, bool rendertarget, int mipLevels=1, int sampleCount=1)"
.br
.ti -1c
.RI "\fBTexture\fP (bool rendertarget, int sizeW, int sizeH, int autoFillData=0, int sampleCount=1)"
.br
.ti -1c
.RI "void \fBFillTexture\fP (DWORD *pix)"
.br
.ti -1c
.RI "void \fBAutoFillTexture\fP (int autoFillData)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBConvertToSRGB\fP (DWORD *linear)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ID3D11Texture2D * \fBTex\fP"
.br
.ti -1c
.RI "ID3D11ShaderResourceView * \fBTexSv\fP"
.br
.ti -1c
.RI "ID3D11RenderTargetView * \fBTexRtv\fP"
.br
.ti -1c
.RI "int \fBSizeW\fP"
.br
.ti -1c
.RI "int \fBSizeH\fP"
.br
.ti -1c
.RI "int \fBMipLevels\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Texture::AutoFillTexture (int autoFillData)\fC [inline]\fP"
ConvertToSRGB(curr); //Require format for SDK - I've been recommended to remove for now\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for OvrvisionSDK from the source code\&.
