.TH "TextureBuffer" 3 "Sun Nov 22 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextureBuffer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextureBuffer\fP (ovrHmd hmd, bool rendertarget, bool displayableOnHmd, Sizei size, int mipLevels, unsigned char *data, int sampleCount)"
.br
.ti -1c
.RI "Sizei \fBGetSize\fP () const "
.br
.ti -1c
.RI "void \fBSetAndClearRenderSurface\fP (\fBDepthBuffer\fP *dbuffer)"
.br
.ti -1c
.RI "void \fBUnsetRenderSurface\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ovrHmd \fBhmd\fP"
.br
.ti -1c
.RI "ovrSwapTextureSet * \fBTextureSet\fP"
.br
.ti -1c
.RI "GLuint \fBtexId\fP"
.br
.ti -1c
.RI "GLuint \fBfboId\fP"
.br
.ti -1c
.RI "Sizei \fBtexSize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OvrvisionSDK from the source code\&.
