.TH "Utility" 3 "Sun Nov 22 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utility \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOutput\fP (const char *fnt,\&.\&.\&.)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OvrvisionSDK from the source code\&.
