.TH "Vertex" 3 "Sun Nov 22 2015" "Version 1.0" "OvrvisionSDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vertex \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVertex\fP (XMFLOAT3 pos, DWORD c, float u, float v)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "XMFLOAT3 \fBPos\fP"
.br
.ti -1c
.RI "DWORD \fBC\fP"
.br
.ti -1c
.RI "float \fBU\fP"
.br
.ti -1c
.RI "float \fBV\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OvrvisionSDK from the source code\&.
